"""
LLM-based AI text detection.

Supports two providers:
  - openai  : Uses the Chat Completions API (gpt-3.5-turbo or better)
  - ollama  : Uses a locally running Ollama instance (e.g. mistral)

The LLM is asked to return a probability [0.0–1.0] that the given
text was generated by an AI. The response is parsed from JSON.
"""

import asyncio
import json
import logging
import re
from typing import Optional

import httpx

from config import get_settings

logger = logging.getLogger(__name__)

DETECTION_PROMPT = """\
You are an expert forensic linguist specialising in distinguishing AI-generated \
text from human-written text.

Analyse the following excerpt and estimate the probability (between 0.0 and 1.0) \
that it was written by an AI language model.

Signals to consider:
- Overly uniform sentence structure and length
- Absence of personal voice, lived experience, or idiosyncratic phrasing
- Generic transitions ("Furthermore", "In conclusion", "It is important to note")
- Unnaturally consistent tone throughout
- Lack of typos, colloquialisms, or spontaneous asides
- Repetitive synonyms or formulaic paragraph structure

Respond with ONLY a valid JSON object — nothing else:
{{"probability": <float 0.0-1.0>, "reasoning": "<one sentence>"}}

Text:
\"\"\"
{text}
\"\"\"\
"""

_MAX_TEXT_CHARS = 800   # ~200 tokens — keeps each request small to respect TPM limits

_RETRY_DELAYS = [5, 15, 30]  # seconds between retries on 429


def _truncate(text: str) -> str:
    return text[:_MAX_TEXT_CHARS] if len(text) > _MAX_TEXT_CHARS else text


def _parse_llm_response(raw: str) -> float:
    """Extract probability float from LLM JSON response."""
    # Try direct JSON parse first
    try:
        data = json.loads(raw.strip())
        return float(data["probability"])
    except (json.JSONDecodeError, KeyError, ValueError):
        pass

    # Fallback: regex extract
    match = re.search(r'"probability"\s*:\s*([0-9.]+)', raw)
    if match:
        return float(match.group(1))

    # Last resort: find any float in [0,1]
    floats = re.findall(r'\b(0?\.\d+|1\.0|0\.0)\b', raw)
    if floats:
        return float(floats[0])

    logger.warning("Could not parse LLM response: %s", raw[:200])
    return 0.5  # neutral fallback


# ---------------------------------------------------------------------------
# OpenAI
# ---------------------------------------------------------------------------
async def _score_openai(text: str, client: httpx.AsyncClient) -> float:
    settings = get_settings()
    prompt = DETECTION_PROMPT.format(text=_truncate(text))

    headers = {
        "Authorization": f"Bearer {settings.openai_api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": settings.openai_model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": settings.openai_max_tokens,
        "temperature": settings.openai_temperature,
    }

    for attempt, delay in enumerate([0] + _RETRY_DELAYS):
        if delay:
            logger.info("Rate limited — retrying in %ds (attempt %d)", delay, attempt + 1)
            await asyncio.sleep(delay)
        try:
            resp = await client.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers,
                json=payload,
                timeout=30.0,
            )
            if resp.status_code == 429:
                continue  # retry
            resp.raise_for_status()
            content = resp.json()["choices"][0]["message"]["content"]
            return _parse_llm_response(content)
        except httpx.HTTPStatusError as exc:
            if exc.response.status_code == 429 and attempt < len(_RETRY_DELAYS):
                continue
            raise

    raise RuntimeError("OpenAI rate limit: all retries exhausted")


# ---------------------------------------------------------------------------
# Ollama
# ---------------------------------------------------------------------------
async def _score_ollama(text: str, client: httpx.AsyncClient) -> float:
    settings = get_settings()
    prompt = DETECTION_PROMPT.format(text=_truncate(text))

    payload = {
        "model": settings.ollama_model,
        "prompt": prompt,
        "stream": False,
        "format": "json",
    }

    resp = await client.post(
        f"{settings.ollama_base_url}/api/generate",
        json=payload,
        timeout=60.0,
    )
    resp.raise_for_status()
    raw = resp.json().get("response", "")
    return _parse_llm_response(raw)


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------
async def score_chunk(text: str, client: httpx.AsyncClient) -> Optional[float]:
    """
    Return AI probability [0,1] for a text chunk using the configured LLM.
    Returns None if the LLM is unavailable / not configured.
    """
    settings = get_settings()

    try:
        if settings.llm_provider == "openai":
            if not settings.openai_api_key:
                logger.warning("OpenAI API key not set — skipping LLM scoring")
                return None
            score = await _score_openai(text, client)

        elif settings.llm_provider == "ollama":
            score = await _score_ollama(text, client)

        else:
            logger.warning("Unknown LLM provider '%s'", settings.llm_provider)
            return None

        # Clamp to valid range
        return max(0.0, min(1.0, score))

    except httpx.HTTPStatusError as exc:
        logger.error("LLM HTTP error %s: %s", exc.response.status_code, exc.response.text[:200])
        return None
    except Exception as exc:
        logger.error("LLM scoring failed: %s", exc)
        return None
